server:
  port: ${PORT:0}

spring:
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        
configuration:
    texto: Configurando entorno Defecto...
